on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render and deploy Book to Netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps: # https://github.com/quarto-dev/quarto-cli/blob/main/src/publish/README.md
      - uses: actions/checkout@v2

      - name: Install Quarto
        uses: cscheid/quarto-actions/setup@v1
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.105
      
      #   quarto publish always renders, so "render" is unnecessary if it comes before publish
      # 
      # - name: Render project
      #   uses: cscheid/quarto-actions/render@v1

      - name: Deploy (to Netlify)
        uses: cscheid/quarto-actions/publish@v1
        with:
          to: netlify
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        # github-token: ${{ secrets.GITHUB_TOKEN }}

        #id: netlify-deploy
        #uses: nwtgck/actions-netlify@v1
        #with:
        #  # The folder the action should deploy. Adapt if you changed in Quarto config
        #  publish-dir: ${{'./_book'
        #  production-branch: main
        #  github-token: ${{ secrets.GITHUB_TOKEN }}
        #  deploy-message:
        #    'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
        #  enable-pull-request-comment: true #  Comment on pull request
        #  enable-commit-comment: true # Comment on GitHub commit
        #  enable-commit-status: true # GitHub commit status 
        #env:
        #  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        #  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        #timeout-minutes: 1